# Generated by Django 2.1.2 on 2019-12-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='status',
            field=models.CharField(default='yes', max_length=200),
            preserve_default=False,
        ),
    ]
