# Generated by Django 2.1.2 on 2019-12-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewbot', '0002_personaldetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='initial_status',
            field=models.CharField(default='Accepted', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='user',
            field=models.CharField(default='Accepted', max_length=100),
            preserve_default=False,
        ),
    ]
